# Generated by Django 2.2.7 on 2020-06-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200619_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
