# Generated by Django 2.2.7 on 2020-06-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200620_0118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
