# Generated by Django 2.2.7 on 2020-07-15 18:13

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_consultant_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
