# Generated by Django 2.2.7 on 2020-07-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200716_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phones',
        ),
    ]
