# Generated by Django 2.2.7 on 2020-07-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200722_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phones',
            new_name='phone',
        ),
    ]
