# Generated by Django 2.2.7 on 2020-07-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.SubCategory', verbose_name='Подкатегория'),
        ),
    ]
