# Generated by Django 2.2.7 on 2020-07-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200719_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('subtext', models.TextField(verbose_name='Подтекст')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='article.Article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Дополнительный раздел в статье',
                'verbose_name_plural': 'Дополнительные разделы в статье',
            },
        ),
    ]
