# Generated by Django 2.2.7 on 2020-07-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articleaddition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleaddition',
            options={'verbose_name': 'Раздел в статье', 'verbose_name_plural': 'Разделы в статье'},
        ),
    ]
