# Generated by Django 2.2.7 on 2020-07-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200724_2209'),
        ('article', '0008_auto_20200723_0118'),
    ]

    operations = [
    ]
