# Generated by Django 2.2.7 on 2020-07-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_merge_20200730_2231'),
        ('article', '0009_merge_20200730_1654'),
    ]

    operations = [
    ]
