# Generated by Django 2.2.7 on 2020-07-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_merge_20200730_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.SubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.SubTypes', verbose_name='Подвид'),
        ),
        migrations.AlterField(
            model_name='article',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Types', verbose_name='Вид'),
        ),
    ]
