# Generated by Django 2.2.7 on 2020-07-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_auto_20200730_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Категория')),
                ('title_kg', models.CharField(max_length=100, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Специальность')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Специальность')),
                ('title_kg', models.CharField(max_length=100, null=True, verbose_name='Специальность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_kg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category-image/', verbose_name='Фотография')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='category-icon/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Подкатегория')),
                ('title_kg', models.CharField(max_length=100, null=True, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Виды')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Виды')),
                ('title_kg', models.CharField(max_length=100, null=True, verbose_name='Виды')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.SubCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='SubTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Подвиды')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Подвиды')),
                ('title_kg', models.CharField(max_length=100, null=True, verbose_name='Подвиды')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Types', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Подвид',
                'verbose_name_plural': 'Подвиды',
            },
        ),
        migrations.CreateModel(
            name='CategoryConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Specialty', verbose_name='Специальность')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='users.Consultant', verbose_name='Консультант')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
