# Generated by Django 2.2.7 on 2020-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20200625_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Комментарии'),
        ),
    ]
