# Generated by Django 2.2.7 on 2020-06-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20200630_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Подвиды')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Types', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Подвид',
                'verbose_name_plural': 'Подвиды',
            },
        ),
    ]
