# Generated by Django 2.2.7 on 2020-07-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20200626_1758'),
        ('forums', '0005_subtypes'),
    ]

    operations = [
    ]
