# Generated by Django 2.2.7 on 2020-07-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
