# Generated by Django 2.2.7 on 2020-07-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_delete_slider'),
        ('forums', '0006_merge_20200702_0515'),
    ]

    operations = [
    ]
