# Generated by Django 2.2.7 on 2020-07-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_category_icon_image'),
        ('forums', '0009_merge_20200704_1806'),
    ]

    operations = [
    ]
