# Generated by Django 2.2.7 on 2020-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_merge_20200708_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='description',
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.TextField(max_length=5000, verbose_name='Вопрос'),
        ),
    ]
