# Generated by Django 2.2.7 on 2020-07-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_auto_20200713_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.SubCategory', verbose_name='Подкатегории'),
        ),
    ]
