# Generated by Django 2.2.7 on 2020-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_auto_20200713_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kg',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='comment',
            name='description_kg',
            field=models.TextField(max_length=5000, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='comment',
            name='description_ru',
            field=models.TextField(max_length=5000, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_kg',
            field=models.TextField(max_length=5000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_ru',
            field=models.TextField(max_length=5000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_kg',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subtypes',
            name='title_kg',
            field=models.CharField(max_length=100, null=True, verbose_name='Подвиды'),
        ),
        migrations.AddField(
            model_name='subtypes',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подвиды'),
        ),
        migrations.AddField(
            model_name='types',
            name='title_kg',
            field=models.CharField(max_length=100, null=True, verbose_name='Виды'),
        ),
        migrations.AddField(
            model_name='types',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Виды'),
        ),
    ]
